# Generated by Django 5.1.5 on 2025-02-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
